import {
  AllowedType,
  AttendanceAction,
  DashboardAction,
  EmployeesAction,
  LeaveManagementAction,
  PayrollAction,
  AssetsAction,
  OffboardingAction,
  ReportsAction,
  RolesandAccessAction,
  EmployeeSelfServiceAction,
  DeviceAction,
  ProfileRequestAction,
} from "./permission";

const super_admin: AllowedType = {
  dashboard: {
    [DashboardAction.View]: true,
    [DashboardAction.Create]: true,
    [DashboardAction.Edit]: true,
    [DashboardAction.Delete]: true,
  },
  employee: {
    [EmployeesAction.View]: true,
    [EmployeesAction.Create]: true,
    [EmployeesAction.Edit]: true,
    [EmployeesAction.Delete]: true,
  },
  attendance: {
    [AttendanceAction.View]: true,
    [AttendanceAction.Create]: true,
    [AttendanceAction.Edit]: true,
    [AttendanceAction.Delete]: true,
    [AttendanceAction.Sync]: true,
  },
  leave_management: {
    [LeaveManagementAction.View]: true,
    [LeaveManagementAction.Create]: true,
    [LeaveManagementAction.Edit]: true,
    [LeaveManagementAction.Delete]: true,
  },
  payroll: {
    [PayrollAction.View]: true,
    [PayrollAction.Create]: true,
    [PayrollAction.Edit]: true,
    [PayrollAction.Delete]: true,
  },
  assets: {
    [AssetsAction.View]: true,
    [AssetsAction.Create]: true,
    [AssetsAction.Edit]: true,
    [AssetsAction.Delete]: true,
  },
  offboarding: {
    [OffboardingAction.View]: true,
    [OffboardingAction.Create]: true,
    [OffboardingAction.Edit]: true,
    [OffboardingAction.Delete]: true,
  },
  reports: {
    [ReportsAction.View]: true,
    [ReportsAction.Create]: true,
    [ReportsAction.Edit]: true,
    [ReportsAction.Delete]: true,
  },
  roles_and_access: {
    [RolesandAccessAction.View]: true,
    [RolesandAccessAction.Create]: true,
    [RolesandAccessAction.Edit]: true,
    [RolesandAccessAction.Delete]: true,
  },
  Employee_self_service: {
    [EmployeeSelfServiceAction.View]: true,
    [EmployeeSelfServiceAction.Create]: true,
    [EmployeeSelfServiceAction.Edit]: true,
    [EmployeeSelfServiceAction.Delete]: true,
  },
  device: {
    [DeviceAction.View]: true,
    [DeviceAction.Create]: true,
    [DeviceAction.Update]: true,
    [DeviceAction.Delete]: true,
    [DeviceAction.Sync]: true,
  },
  profile_requests: {
    [ProfileRequestAction.View]: true,
    [ProfileRequestAction.Create]: true,
    [ProfileRequestAction.Edit]: true,
    [ProfileRequestAction.Delete]: true,
    [ProfileRequestAction.Review]: true,
  },
};

const hr_admin: AllowedType = {
  dashboard: {
    [DashboardAction.View]: true,
    [DashboardAction.Create]: false,
    [DashboardAction.Edit]: false,
    [DashboardAction.Delete]: false,
  },
  employee: {
    [EmployeesAction.View]: true,
    [EmployeesAction.Create]: true,
    [EmployeesAction.Edit]: true,
    [EmployeesAction.Delete]: true,
  },
  attendance: {
    [AttendanceAction.View]: true,
    [AttendanceAction.Create]: true,
    [AttendanceAction.Edit]: true,
    [AttendanceAction.Delete]: false,
    [AttendanceAction.Sync]: true,
  },
  leave_management: {
    [LeaveManagementAction.View]: true,
    [LeaveManagementAction.Create]: true,
    [LeaveManagementAction.Edit]: true,
    [LeaveManagementAction.Delete]: true,
  },
  payroll: {
    [PayrollAction.View]: true,
    [PayrollAction.Create]: true,
    [PayrollAction.Edit]: true,
    [PayrollAction.Delete]: false,
  },
  assets: {
    [AssetsAction.View]: true,
    [AssetsAction.Create]: true,
    [AssetsAction.Edit]: true,
    [AssetsAction.Delete]: true,
  },
  offboarding: {
    [OffboardingAction.View]: true,
    [OffboardingAction.Create]: true,
    [OffboardingAction.Edit]: true,
    [OffboardingAction.Delete]: false,
  },
  reports: {
    [ReportsAction.View]: true,
    [ReportsAction.Create]: false,
    [ReportsAction.Edit]: false,
    [ReportsAction.Delete]: false,
  },
  roles_and_access: {
    [RolesandAccessAction.View]: true,
    [RolesandAccessAction.Create]: false,
    [RolesandAccessAction.Edit]: false,
    [RolesandAccessAction.Delete]: false,
  },
  Employee_self_service: {
    [EmployeeSelfServiceAction.View]: true,
    [EmployeeSelfServiceAction.Create]: false,
    [EmployeeSelfServiceAction.Edit]: true,
    [EmployeeSelfServiceAction.Delete]: false,
  },
  device: {
    [DeviceAction.View]: true,
    [DeviceAction.Create]: true,
    [DeviceAction.Update]: true,
    [DeviceAction.Delete]: true,
    [DeviceAction.Sync]: true,
  },
  profile_requests: {
    [ProfileRequestAction.View]: true,
    [ProfileRequestAction.Create]: false,
    [ProfileRequestAction.Edit]: true,
    [ProfileRequestAction.Delete]: false,
    [ProfileRequestAction.Review]: true,
  },
};

const employee: AllowedType = {
  dashboard: {
    [DashboardAction.View]: true,
    [DashboardAction.Create]: false,
    [DashboardAction.Edit]: false,
    [DashboardAction.Delete]: false,
  },
  employee: {
    [EmployeesAction.View]: true,
    [EmployeesAction.Create]: false,
    [EmployeesAction.Edit]: true,
    [EmployeesAction.Delete]: false,
  },
  attendance: {
    [AttendanceAction.View]: true,
    [AttendanceAction.Create]: true,
    [AttendanceAction.Edit]: true,
    [AttendanceAction.Delete]: false,
    [AttendanceAction.Sync]: true,
  },
  leave_management: {
    [LeaveManagementAction.View]: true,
    [LeaveManagementAction.Create]: true,
    [LeaveManagementAction.Edit]: false,
    [LeaveManagementAction.Delete]: false,
  },
  payroll: {
    [PayrollAction.View]: true,
    [PayrollAction.Create]: false,
    [PayrollAction.Edit]: false,
    [PayrollAction.Delete]: false,
  },
  assets: {
    [AssetsAction.View]: true,
    [AssetsAction.Create]: true,
    [AssetsAction.Edit]: false,
    [AssetsAction.Delete]: false,
  },
  offboarding: {
    [OffboardingAction.View]: false,
    [OffboardingAction.Create]: false,
    [OffboardingAction.Edit]: false,
    [OffboardingAction.Delete]: false,
  },
  reports: {
    [ReportsAction.View]: false,
    [ReportsAction.Create]: false,
    [ReportsAction.Edit]: false,
    [ReportsAction.Delete]: false,
  },
  roles_and_access: {
    [RolesandAccessAction.View]: false,
    [RolesandAccessAction.Create]: false,
    [RolesandAccessAction.Edit]: false,
    [RolesandAccessAction.Delete]: false,
  },
  Employee_self_service: {
    [EmployeeSelfServiceAction.View]: true,
    [EmployeeSelfServiceAction.Create]: false,
    [EmployeeSelfServiceAction.Edit]: true,
    [EmployeeSelfServiceAction.Delete]: false,
  },
  device: {
    [DeviceAction.View]: false,
    [DeviceAction.Create]: false,
    [DeviceAction.Update]: false,
    [DeviceAction.Delete]: false,
    [DeviceAction.Sync]: true,
  },
  profile_requests: {
    [ProfileRequestAction.View]: true,
    [ProfileRequestAction.Create]: true,
    [ProfileRequestAction.Edit]: false,
    [ProfileRequestAction.Delete]: false,
    [ProfileRequestAction.Review]: false,
  },
};

export const allPermission = {
  super_admin,
  hr_admin,
  employee,
};
